<!doctype html>
<html lang="en">
<head>
    <title>Dealing with an Exception Is One Thing</title>
    <meta name="description" content="Nothing new, but I keep seeing violating of this rule again and again. Let's explain why it is bad.">
    <meta name="author" content="Tomas Tulka">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.png">

    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="@tomas_tulka">
    <meta name="twitter:creator" content="@tomas_tulka">
    <meta name="twitter:title" content="Dealing with an Exception Is One Thing by Tomas Tulka">
    <meta name="twitter:image:src" content="https://blog.ttulka.com/assets/img/blog.jpg">
    <meta property="og:url" content="https://blog.ttulka.com/dealing-with-an-exception-is-one-thing" />
    <meta property="og:type" content="article" />
    <meta property="og:title" content="Dealing with an Exception Is One Thing by Tomas Tulka" />
    <meta property="og:image" content="https://blog.ttulka.com/assets/img/blog.jpg">

    <link href="/assets/css/syntaxhighlighter.css" rel="stylesheet">
    <link href="/assets/css/blog.2.7.css" rel="stylesheet">
</head>
<body>

<header class="header">
    <div class="container">
        <nav class="nav">
            <a class="active" href="/">Home</a>
            <a href="/about">About</a>
        </nav>
        <div class="ext-links">
            <a href="https://twitter.com/tomas_tulka"><img src="/assets/img/twitter.png"></a>
            <a href="https://github.com/ttulka"><img src="/assets/img/github.png"></a>
            <a href="#" class="theme"><img src="/assets/img/theme.png"></a>
        </div>
    </div>
</header>

<main class="main">

    <article class="blog-post">
    <h1 class="blog-post__title">Dealing with an Exception Is One Thing</h1>
    <p class="blog-post__meta">2019-02-09 by Tomas Tulka</p>
    <p>Nothing new, but I keep seeing violating of this rule again and again. Let's explain why it is bad.</p>
    <hr>
    <p>In his famous book Clean Code, Robert C. Martin writes:</p>
<blockquote class="quote">Functions should do one thing. Error handling is one thing.</blockquote>
<p>This is a very simple principle, but I see it in action only rarely. What's actually wrong with that?:</p>
<pre class="brush: java">class TextFile {
  private final Path path;

  TextFile(Path path) { this.path = path; }

  boolean save(String content) {
    try {
      byte[] bytes = content.getBytes("UTF-8");
      Files.write(this.path, bytes);

      return true;

    } catch (IOException e) {
      // log the exception
    }
    return false;
  }
}
</pre>
<p>The thing here is we are trying to inform the client about the fact the save operation was successful or not. But this is not what the method is supposed to do, <strong>the method should save the content, period</strong>.</p>
<p>Exposing a boolean return value the method says to its client that the error is some kind of correct behavior. But the client doesn't expect such a behavior, the client simply expect the content to be saved. If not, it is an incorrect behaviour and an exception should occur.</p>
<p>The <code>save</code> method is different from, for example, a <code>boolean&nbsp;readable()</code> method. We expect this method to answer the question if the file is readable or not. And <code>false</code> is a valid answer in this case.</p>

<p>What's the right approach? If you prefer unchecked exceptions (I do), consider the following:</p>
<pre class="brush: java">class TextFile {
  private final Path path;

  TextFile(Path path) { this.path = path; }

  void save(String content) {
    try {
      byte[] bytes = content.getBytes("UTF-8");
      Files.write(this.path, bytes);

    } catch (IOException e) {
      throw new FileNotSavedException("Cannot save a file: " + path, e);
    }
  }
}

class FileNotSavedException extends RuntimeException {

  FileNotSavedException(String message, Throwable cause) {
     super(message, cause);
  }
}
</pre>
<p>Now, the <code>save</code> method is doing exactly what we expect from it: saves a context in a file. When this isn't for whatever reason possible, an exception is thrown and it's up to <strong>the client to deal with the situation</strong>.</p>

<p>Have an exceptional day!</p>

</article>

<aside class="blog-tags">
    
    <a href="/tag/Programming" class="tag">Programming</a>
    
    
</aside>

<aside class="blog-comments">
    <h2>Leave a message</h2>
    <p class="leave-message">You can add a comment to this post by <a href="https://github.com/ttulka/blog-content/edit/main/site/comments/dealing-with-an-exception-is-one-thing.json">opening a pull request</a> (see <a href="https://github.com/ttulka/blog-content#add-a-new-comment">HowTo</a>).</p>

    
    
    
</aside>

</main>

<footer class="footer">
    <div class="container">
        <div class="footer__extended">Â© 2021 Tomas Tulka (ttulka)</div>
        <div class="footer__menu">
            <a href="/">Home</a> |
            <a href="/privacypolicy/">Privacy Policy</a>
        </div>
    </div>
</footer>

<script src="/assets/js/darktheme.js"></script>
<script src="/assets/js/syntaxhighlighter.min.js" defer></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-ZKWY8T55EM"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-ZKWY8T55EM');
</script>

</body>
</html>